### ISSUE TITLE
Puerto Rico flag changes to US flag while typing the number

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#108]
Not sure about the extent of the issue, seems to be related to countries with the same dial code (they're both `+1`)

Steps to reproduce:
1. Open demo page http://patw0929.github.io/react-intl-tel-input/
2. Select Puerto Rico
3. Type `1234`
4. As soon as you type `4`, the flag changes to `US` flag

Is this expected? Any way to disable this behavior?

**Comment by patw0929** [comment]
Yes, this is [North American Numbering Plan (NANP)](https://en.wikipedia.org/wiki/North_American_Numbering_Plan), and the related function in 'react-intl-tel-input` is called `isUnknownNanp`.

**Comment by brunops** [comment]
Sure, I understand that, but why would want the flag to change? Is it possible to disable this feature?
In case the answer is "no", would you be willing to implement it or take a PR?

**Comment by patw0929** [comment]
We could revise this line to disable this feature:

From:
```js
if (!alreadySelected || this.isUnknownNanp(number, dialCode)) {
```

To:
```js
if (!alreadySelected) {
```

But I'm not sure if it would cause other issue.

**Comment by patw0929** [comment]
@brunops: How about a option of keeping flag in unknown NANP? (PR #110)

**Comment by brunops** [comment]
Hey Patrick, 
Sorry for the delayed response. I like the idea of being able to turn this feature off in #110 

thanks!
