### ISSUE TITLE
Remove `eval` call

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#111]
Any reason to use `eval` here? This is actually a problem for me, as our standards simply do not allow `eval`s to be used.
https://github.com/patw0929/react-intl-tel-input/blob/master/src/containers/IntlTelInputApp.js#L594

If it's data, why not relpace it with `JSON.parse(data)`?

**Comment by patw0929** [comment]
It's not data. It's a `.js` content.
I make another way to execute the dynamic loaded js content, please take a look about PR #112.

**Comment by brunops** [comment]
@patw0929 nice! a couple of tests failing, but better than using `eval` if it works 👍

**Comment by patw0929** [comment]
Hmmm... I have fixed the failed tests with `eval` in tests. :confused:
