### ISSUE TITLE
Use bundle-loader to load libphonenumber.js and avoid globals

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#113]
I just want to open a discussion, it's not a critical issue.

I was playing with webpack's `bundle-loader` for another project and thought it might be a nice solution to load `libphonenumber.js` here too. It basically allows you to generate other bundles that may or may not be asynchronously loaded. see https://github.com/webpack/bundle-loader

It would allow the loading of `google-libphonenumber` code instead of the version currently being distributed here and prevent variables from leaking to the global scope too.

This is a sample of how it would work (code inside `loadUtils` method):

``` js
    var self = this;

    require("bundle?google-libphonenumber")(function(bundle) {
      // save a reference of the library in the component
      // so all other uses don't depend on globals
      self.libphonenumber = bundle;

      self.utilsScriptDeferred.resolve();
    });
```

Some points:
1. `google-libphonenumber` module seems bigger than the one in this probject, but it doesn't leak globals as far as I know. see https://github.com/seegno/google-libphonenumber
2. Lib code is still outside of the main `react-intl-tel-input` bundle and loaded asynchronously, so no size change there.
3. `bundle-loader` takes a `lazy` option, which allows us to load the library only if `utilsScript` is passed
4. The `google-libphonenumber` API is different than the one here included here, so the change might not be super straightforward

Let me know your thoughts on this

**Comment by patw0929** [comment]
Thank you for the advice!

I have made a branch here: https://github.com/patw0929/react-intl-tel-input/tree/bundle-loader-utils
Also rewrote the tests, but one weird thing is that the coverage is always 100%, seems only grab the `webpack.test.config.js`.

Any idea?

**Comment by brunops** [comment]
That was fast 👍 
I'll take a look at the tests and see if I can find something. I never used `mocha-webpack` before, is it so the webpack require's work? I usually use `rewire` for that, but I'll take a look later and let you know, thanks!

**Comment by mrlundis** [comment]
Any updates on this?

**Comment by atuttle** [comment]
Even though I'm using webpack, if this change results in webpack becoming a required dependency for this component; (and a specific loader, too!) then I would vote against it.

**Comment by superhit0** [comment]
@patw0929 
I think we can do something like this.

[Making UtilScript Optional](https://github.com/patw0929/react-intl-tel-input/compare/master...superhit0:util-script-optional?expand=1).

Any thoughts on this issue/approach?

**Comment by superhit0** [comment]
closing this as the libphonenumber has been moved & has been made an integral part of the repo
