### ISSUE TITLE
Update to react 15

### ISSUE THREAD

**Issue by LarsMq73** [patw0929/react-intl-tel-input#120]
Hi,
can this (cool) component be updated to react 15.1.0?
I've done this in a fork, but I'm not sure if it's used by you somewhere else and this update will produce problems for you.
The test ran ok, but I get some linting errors (no-underscore-dangle, react/jsx-first-prop-new-line, react/prefer-stateless-function, no-restricted-syntax, comma-spacing) where I'm not sure if you want to follow them or not (I would ;) )
thanks for a reply
Lars

**Comment by patw0929** [comment]
Sure! Thanks a lot! 
Please send a pull request to this repo.

I think the linting errors might be related with the version of `eslint-config-airbnb`...?

**Comment by LarsMq73** [comment]
Yes, might be - should I fix the linting errors or would you prefer to adjust the linting setup to your own "needs"?

**Comment by patw0929** [comment]
Hmm... I prefer to revise the linting config.

**Comment by LarsMq73** [comment]
ok. Than I just send you a pull request and you check the linting config, ok?

**Comment by patw0929** [comment]
OK, no problem! 
I'll check it later, thank you!

**Comment by LarsMq73** [comment]
pull request send.
Even I'm developer since several years, but it's my first "coding" contribution... So - check carefully;) hopefully it's fine 

Lars

**Comment by LarsMq73** [comment]
sorry, I think it should be closed if the update is release...

**Comment by adamtrilling** [comment]
I've been trying to get this to work on React 15 for the last day or so. The code works fine, but I've got failing tests due to timeouts. It's very weird...it appears that each successive call to ReactDom.render() takes longer and longer.

**Comment by LarsMq73** [comment]
Hm, the time I've tested, all 55 passed (npm run test)... Unfortunately I now have to feet my kids and cannot try again. Tomorrow or maybe in the evening (I'm in germ

**Comment by LarsMq73** [comment]
any)

**Comment by patw0929** [comment]
Hey guys, I update my node.js to `v6.2.2`, and then the test is speed up, the test result is also get success.

Released this version as `v3.1.0`.

**Comment by LarsMq73** [comment]
Hi,
of course, the node version;) I recently update node / npm versions, I forgot to note this here;)
Thanks for merging!
It works fine, now I also can create my npm-shrinkwrap again ;)
best regards
Lars
