### ISSUE TITLE
Numbers not spaced after updates

### ISSUE THREAD

**Issue by Zephir77167** [patw0929/react-intl-tel-input#124]
Hello,

I just updated your (amazing) lib from 2.3.x to 3.1.1 and I lost a pretty neat feature, the spacing of the phone number (which can be seen in the placeholder for example).

Could you please take a look at this please?

Thanks in advance!

**Comment by patw0929** [comment]
Hi @Zephir77167,

Unfortunately, the auto format feature was removed in v3.
(As the React ported version, I follow the original project's feature.)

The detail reason about why removing auto format, please read here:
https://github.com/jackocnr/intl-tel-input/issues/346

Thanks!

**Comment by Zephir77167** [comment]
Ok, thank you for the info!
