### ISSUE TITLE
Number is not formatted

### ISSUE THREAD

**Issue by thalseth** [patw0929/react-intl-tel-input#127]
Hi @patw0929 :)
The formatting is not working when you input a number. Tested the demo: http://patw0929.github.io/react-intl-tel-input/. 

Do you have any idea what could cause this issue?

**Comment by patw0929** [comment]
Hmm... it seems to be the same issue with #124.
Not support in new version, sorry. :sweat_smile:

**Comment by thalseth** [comment]
I understand 😢
