### ISSUE TITLE
isGoodBrowser throws an error when trying to render from server

### ISSUE THREAD

**Issue by mgibeau** [patw0929/react-intl-tel-input#129]
https://github.com/patw0929/react-intl-tel-input/blob/v3.0.0/src/containers/IntlTelInputApp.js#L116

I'm using the library in an isomorphic application and since `isGoodBrowser` is trying to access the document object, it crashes when node resolves the module. 

It doesn't seem like this is being used anymore. I have since forked the library and applied the fix from the 3.0.0 tag because I'm still using react 0.14 but I could open a pull request with the changes if you think that makes sense.

Thanks!

**Comment by ayoola-solomon** [comment]
@mgibeau I am also using the module in an isomorphic application but the issue I am having is `module.js:442
    throw err;
    ^
Error: Cannot find module 'file?name=libphonenumber.js!../../../node_modules/react-intl-tel-input/dist/libphonenumber.js'`

@mgibeau I need your input please.

**Comment by mgibeau** [comment]
@ayoola-solomon Sorry, I don't maintain this library, from what I can tell, the error you're getting is a completely different issue, it might not have anything to do with your app being isomorphic.

I suggest you open a new issue for this, it would also help if you included an example describing how you are using it.

**Comment by atuttle** [comment]
Since #144 was merged, should this be closed?

**Comment by mgibeau** [comment]
Yes, closing, thanks @patw0929 !
