### ISSUE TITLE
How can i get international phone number?

### ISSUE THREAD

**Issue by MrZaYaC** [patw0929/react-intl-tel-input#13]
I am about this future:
**getNumber**
Get the current number in the given format (defaults to E.164 standard). The different formats are available in the enum intlTelInputUtils.numberFormat - taken from here. Requires the utilsScript option. Note that even if nationalMode is enabled, this can still return a full international number.

https://github.com/Bluefieldscom/intl-tel-input#public-methods

**Comment by MrZaYaC** [comment]
I made Pull request #14 
Can you merge it?

**Comment by patw0929** [comment]
Merged. Thank you for your contribution! :+1:
