### ISSUE TITLE
selected-flag title is equal to undefined: +undefined

### ISSUE THREAD

**Issue by viktop** [patw0929/react-intl-tel-input#135]
http://patw0929.github.io/react-intl-tel-input/

Screenshot attached
<img width="1353" alt="screen shot 2016-08-16 at 4 03 47 pm" src="https://cloud.githubusercontent.com/assets/6886520/17713863/15ddd20a-63cb-11e6-8e83-75a12cb904d8.png">

**Comment by patw0929** [comment]
Fixed in v3.1.2.

**Comment by viktop** [comment]
Thanks!
