### ISSUE TITLE
Expose tabIndex as configurable

### ISSUE THREAD

**Issue by danwarner** [patw0929/react-intl-tel-input#151]

**Comment by atuttle** [comment]
@danwarner I'm curious why you've closed this. Seems like a reasonable request to me. Is there some way to accomplish it without a change to the module?

**Comment by ohyde** [comment]
I'm looking for this feature too, is there a reason I'm not seeing for why this was closed or is it worth me working on a PR?

**Comment by firestar300** [comment]
+1
