### ISSUE TITLE
Bound function to the window's scroll event is not being unbound when the component is unmounted

### ISSUE THREAD

**Issue by ricardo-quinones** [patw0929/react-intl-tel-input#152]
![image](https://cloud.githubusercontent.com/assets/5261979/19011266/08063250-875f-11e6-9da7-1eb58420c0a4.png)

I have a quick PR that fixes this if you'd be up for reviewing it.

**Comment by patw0929** [comment]
Oh, sure! Please provide your PR, thanks a lot!
