### ISSUE TITLE
Value property should force input value

### ISSUE THREAD

**Issue by chris-verclytte** [patw0929/react-intl-tel-input#165]
At the moment, the 'value' property allow to pass a value to input but does not constrain input value. 
I would expect this property to allow controlled input by an HOC component. 

My use case is that I am using [redux-form](https://github.com/erikras/redux-form) lib for managing my forms and I would like redux-form to constrain react-intl-tel-input value (Redux-form aim to sync value from input with value stored in Redux in order to allow complex validation among other features).

But when using react-intl-tel-input I can't set a specific value because the input value is based on `this.state.value` which is updated on onChange event without any control.

Reading the code, it seems that currently value passed from props is only used for setting initial input value [here](https://github.com/patw0929/react-intl-tel-input/blob/master/src/containers/IntlTelInputApp.js#L473). 
Maybe this should rather be called defaultValue and value prop should be kept for constraining value from outside the component ?

What do you think about that ?

**Comment by amitzur** [comment]
I think this issue can be closed

**Comment by nutboltu** [comment]
Fixed in  #166
