### ISSUE TITLE
disabled state doesn't update an input field

### ISSUE THREAD

**Issue by mic3ael** [patw0929/react-intl-tel-input#168]
I pass to an IntlTelInput component disable={my_disable}, my_disable is boolean variable, in the first time it is true and the IntlTelInput is disabled but when the my_disabled became false the IntlTelInput still disabled I can't modify input field.

Thanks for the help, Michael.

**Comment by patw0929** [comment]
Forgot to update `disabled` in `componentWillReceiveProps`.
Fixed in v4.1.0.

**Comment by nutboltu** [comment]
Fixed. moved the logic to `getDerivedStateFromProps` by @patw0929
