### ISSUE TITLE
New prop defaultValue doesn't fire onPhoneNumberChange on mount

### ISSUE THREAD

**Issue by Zephir77167** [patw0929/react-intl-tel-input#170]
Hi,

I was using this lib as an uncontrolled component, and since this PR: https://github.com/patw0929/react-intl-tel-input/pull/166 `onPhoneNumberChange` is not fired on mount. Why would that be useful? I need the parameters of the function to handle the value changes (status, countryData, ...).

Could you please fire it at mount like it used to?

Thanks in advance.

@chris-verclytte

**Comment by Zephir77167** [comment]
Created a PR: https://github.com/patw0929/react-intl-tel-input/pull/171

**Comment by patw0929** [comment]
merged and published as v4.1.0.

**Comment by Zephir77167** [comment]
Thanks to you! I close this issue as it is now resolved :)
