### ISSUE TITLE
Flag doesn't automatically change when `value` prop is defined

### ISSUE THREAD

**Issue by chipit24** [patw0929/react-intl-tel-input#172]
When I make the phone input controlled by adding a `value` prop, the flag no longer automatically updates based on the value entered.

Ex.
```
<ReactPhoneInput
  value={this.state.phoneNumber}
  onPhoneNumberChange={(isValid, phoneNumber) => this.setState({phoneNumber})}
  utilsScript={require('file!react-intl-tel-input/dist/libphonenumber')}
  defaultCountry={'us'}/>
```

The US flag appears initially, but if I enter any non-US phone number, the flag remains the same. This problem doesn't occur if I remove the `value` prop.

Adding a ref and setting the flag manually via `setFlag` works, but only if the country code is in lower case (ex. `'CA'` sets the flag to `undefined: +undefined` but `'ca'` works fine).

**Comment by nutboltu** [comment]
Fixed in #178
