### ISSUE TITLE
null is not an object (evaluating 'this.tel.getAttribute')

### ISSUE THREAD

**Issue by adrienharnay** [patw0929/react-intl-tel-input#181]
Hi,

I'm using react-intl-tel-input in my app, and Sentry is often catching an error `null is not an object (evaluating 'this.tel.getAttribute')`, which comes from IntlTelInputApp, l.548.

Don't know if this is breaking for something or not.

**Comment by Zephir77167** [comment]
Hey, Sentry is reporting this error everyday on my website. I could do a PR to fix the problem, but would like to have a chat first to get some context, if possible. Thanks!

**Comment by patw0929** [comment]
Thank you, PRs are welcomed.
Sorry for not have much time on this project. What do you think about this issue?

**Comment by Zephir77167** [comment]
No problem at all, I understand completely.

I think we have two options:
- change [this line](https://github.com/patw0929/react-intl-tel-input/blob/bacea02583f0ee463ef57b341db9d60103d66317/src/components/IntlTelInputApp.js#L558) to `const max = this.tel ? this.tel.getAttribute('maxlength') : number;`
- try changing [this line](https://github.com/patw0929/react-intl-tel-input/blob/bacea02583f0ee463ef57b341db9d60103d66317/src/components/IntlTelInputApp.js#L225) to ```
if (ref) {
  this.tel = ref;
}
```

Either way, I don't understand how `this.tel` could ever become null. Tell me what you think!

**Comment by patw0929** [comment]
I prefer the first one, but in other parts (e.g., [here](https://github.com/patw0929/react-intl-tel-input/blob/bacea02583f0ee463ef57b341db9d60103d66317/src/components/IntlTelInputApp.js#L276)) might have same issue.
Hmm, I'm curious too. Let me guess... could it be the moment of unmounting the component? When unmounting, ref could be `null`.

**Comment by Zephir77167** [comment]
Oddly, I have never had any report for this other line, but I understand your point. Your explanation might in fact be right!

Do you want me to file the PR (including a fix for the first line, and possibly other occurences of `this.tel`)?

**Comment by patw0929** [comment]
Yes, please help the PR based on current master branch.
Thank you! 👍

**Comment by Zephir77167** [comment]
PR opened, sorry about the delay! I think I covered the possible cases we talked about. Feedback welcomed!
