### ISSUE TITLE
How to use with last google-libphonenumber package

### ISSUE THREAD

**Issue by benjamindulau** [patw0929/react-intl-tel-input#182]
Hey,

I'd like to use a more recent version of the libphonenumber library, but I just can't figure out how to do this.

Is there any way to use the one from https://github.com/ruimarinho/google-libphonenumber ?
How did you build the libphonenumber.js file under dist/ folder ?

Thanks!

**Comment by Arshadf** [comment]
I am having the same issue with the newly added Telco in Egypt which couldn't be validated by this version of google-libphonenumber library. Will really appreciate any suggestion

**Comment by akramAtVenD** [comment]
Hi,
I am also getting the same issue. Will really appreciate any suggestion or solutions.

Thanks.

**Comment by superhit0** [comment]
@benjamindulau @Arshadf @akramAtVenD 

Hi, The version of `google-libphonenumber` has been updated to `v8.9.9` in the version of `v5.0.7` of `react-intl-tel-input`, which is as of now the latest version of `google-libphonenumber`. 

Closing this issue as the problem has already been resolved.
