### ISSUE TITLE
formatAsYouType option

### ISSUE THREAD

**Issue by AlexandreBernard** [patw0929/react-intl-tel-input#186]
Hey,

more a question than an issue but is there a way to format the number as we type?

I've seen google phone library has the methods to do it

is there a way to do it already? otherwise consider this as a feature suggestion

Also, I found difficult to end up with a consistant value format on the onPhoneNumberChange callback. I ended up finding intlTelInputUtils.formatNumber(value, country.iso2, 0) but this is undocumented and would ideally be another possible new option too

Alexandre

**Comment by amitzur** [comment]
I believe the `format` option does what you ask for in your first point

**Comment by superhit0** [comment]
this feature is there
