### ISSUE TITLE
Blank Flag when limiting coutries

### ISSUE THREAD

**Issue by darkenvy** [patw0929/react-intl-tel-input#187]
When using onlyCountries, a blank flag appears when inserting a number outside of the list of allowed countries.

**Comment by darkenvy** [comment]
See PR 188. I ended up making a patch. https://github.com/patw0929/react-intl-tel-input/pull/188

**Comment by patw0929** [comment]
Hey @darkenvy, thank you for your contribution! 🙇 
I've merged it & publish as v4.3.1. 👍
