### ISSUE TITLE
No Changelog

### ISSUE THREAD

**Issue by jedlikowski** [patw0929/react-intl-tel-input#190]
I've noticed there is no `CHANGELOG.md` file in this project and no changes are listed in releases. It's impossible to know if it's safe for us to upgrade the package to a newer version :D

**Comment by patw0929** [comment]
Good point!
But I'm quite busy these days, so I'll arrange released version's release notes when I have time.
It'd be greatly appreciated if anyone could help.

**Comment by nutboltu** [comment]
Fixed in #250
