### ISSUE TITLE
Unable to delete countryCode

### ISSUE THREAD

**Issue by bartoszl** [patw0929/react-intl-tel-input#197]
It is impossible to deletedial code at the moment after it's filled in. After pressing backspace at least one digit remains, additionally after pressing backspace again, the dial code fills in again. In release 4.3.0 that was not the case.

**Comment by patw0929** [comment]
@MatthewAnstey Could you help to check this issue?
It seems related to #195.
Thanks!

**Comment by MatthewAnstey** [comment]
@patw0929 

Sure. Seems to happen when its uncontrolled and separateDialCode is true. Will look into it.

**Comment by patw0929** [comment]
Fixed and released as v4.3.4.
Thanks for @MatthewAnstey's help!
