### ISSUE TITLE
Placeholder doesn't change when `placeholder` or `customPlaceholder` change

### ISSUE THREAD

**Issue by adrienharnay** [patw0929/react-intl-tel-input#203]
Hey,

When I change the value of the props `placeholder` or `customPlaceholder`, it doesn't change the state of `IntlTelInputApp`, and therefore doesn't rerender. I would need to dynamically change either one of them (e.g. hiding placeholder and displaying error when there is one).

Would you mind if I filed a PR for this change?

Thanks for this project! :+1:

**Comment by patw0929** [comment]
Definitely! 👍 Thanks for your help!
