### ISSUE TITLE
Cursor moves to end of input when removing digits from formatted number

### ISSUE THREAD

**Issue by adrienharnay** [patw0929/react-intl-tel-input#205]
Hey,

When using the `format` prop and input a complete number, then delete a digit (e.g. the second one), the cursor jumps to the end of the input.

Reproduction:
- connect to [live demo](http://patw0929.github.io/react-intl-tel-input/)
- input a complete number (e.g. french, 0611111111)
- number gets formatted
- remove the 6
- the cursor will jump after the 1s

Could we find a way to prevent this?

Thanks!

**Comment by superhit0** [comment]
Keeping this issue open after the merge of fix so that people can comment here in order to report if they find issues with fix.

**Comment by adrienharnay** [comment]
Hey, thanks for the fix! I think we can close the issue, it will get reopened if someone finds an issue 🙂

**Comment by superhit0** [comment]
Closing for now because the fix was provided.
