### ISSUE TITLE
Node will stop at 91% when import libphonenumber

### ISSUE THREAD

**Issue by Loongwoo** [patw0929/react-intl-tel-input#212]
`import 'file?name=libphonenumber.js!../../../node_modules/react-intl-tel-input/dist/libphonenumber.js';
This code will cause Node.js stoped at 91% and CPU usage is high. 
Do you have any idea for this issue? 
Thanks.

**Comment by superhit0** [comment]
@Loongwoo Can you try like this `import 'react-intl-tel-input/dist/libphonenumber.js';` ?

If it still does not work, can you please post your logs & system specs please, including node/npm version?

**Comment by Loongwoo** [comment]
`utilsScript="../../../node_modules/react-intl-tel-input/dist/libphonenumber.js"`

Fixed.
