### ISSUE TITLE
Libphonenumber.js file from google is outdated.

### ISSUE THREAD

**Issue by superhit0** [patw0929/react-intl-tel-input#216]
It does not include the new phone number series and shows them as invalid.

For example, Mobile numbers starting from 6 like `6xxxxxxxxx` are considered invalid for India, but they are actually valid and if you try to validate from googlei18n/libphonenumber directly, it says as `valid`.

Also, can you also share the process for building the libphonenumber file in the repository, it is not same as the `demo.js`  from the [google's](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0ahUKEwihrZq0ks7bAhWHq48KHbxcAPIQFgg4MAE&url=https%3A%2F%2Fgithub.com%2Fgooglei18n%2Flibphonenumber&usg=AOvVaw0JK61fpE1M2JvKEIGeTy0D) repository.

If possible, I would like to raise a PR for this.

**Comment by patw0929** [comment]
Actually the `libphonenumber.js` is copied from [intl-tel-input](https://github.com/jackocnr/intl-tel-input)'s compiled utils.js. The original source is compile from [src/js/utils.js](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js), but unfortunately the content is not compatible with current react-intl-tel-input.

It will be great If you or someone can help to figure the correct way to compile the newest utils.js and make it compatible. Thanks!

**Comment by superhit0** [comment]
@patw0929 Can you please look at this PR [#220](https://github.com/patw0929/react-intl-tel-input/pull/220)?

Upgrading the version to 8.9.9.

This solves the current issue.

**Comment by patw0929** [comment]
Cool. I'm curious about the difference of intl-tel-input's compiled version? If we need to update next version next time, what should we do?

**Comment by superhit0** [comment]
Well, if you want to upgrade the complied version, you have to compile it manually and add it to the repository.
As you have to use closure-complier](https://github.com/googlei18n/libphonenumber/tree/master/javascript) , to compile this [file](https://github.com/jackocnr/intl-tel-input/blob/master/src/js/utils.js).

**Comment by patw0929** [comment]
Oh, thanks, I knew this part. 

What I am curious about is the difference between #220 and the compiled utils.js in intl-tel-input's reoo.
I've tried to copy the intl-tel-input's compiled version long time ago, but seems some function is not exist then causing some issues.

However it seems no problem now :P 
Will check and merge the PR later if everything is ok.

**Comment by superhit0** [comment]
@patw0929 Since, `libphonenumber@8.7.0` present currently in the repo, the libphonenumber in [#220](https://github.com/patw0929/react-intl-tel-input/pull/220) has updated metadata.

One use case difference is in funtionality is -
Mobile numbers starting from 6 like `6xxxxxxxxx` are considered invalid for India according to `libphonenumber@8.7.0`, but they are actually valid and if you try to validate from `libphonenumber@8.9.9`, it says as valid. Which is correct as Mobile numbers of pattern `6xxxxxxxxx` were recently added by government in last few months & google has updated them in latest version of `libphonenumber@8.9.9`

**Comment by patw0929** [comment]
Thank you for the contribution!
Merged & published as v5.0.7.

**Comment by superhit0** [comment]
Thank you
