### ISSUE TITLE
Class 'expanded' stays on the wrapper when dropdown is closed

### ISSUE THREAD

**Issue by ertrzyiks** [patw0929/react-intl-tel-input#218]
Hey, is there any particular reason for the class `expanded` to stay on the wrapper after dropdown is closed?

### Original DOM:
<img width="968" alt="screen shot 2018-06-29 at 09 27 00" src="https://user-images.githubusercontent.com/2437969/42078992-bd3ec5e6-7b7e-11e8-8943-92ebc467cbea.png">

### After open and close country code dropdown
![screen shot 2018-06-29 at 09 27 07](https://user-images.githubusercontent.com/2437969/42079008-ca8ec638-7b7e-11e8-9b01-f594b79701e5.jpg)

**Comment by MilosMosovsky** [comment]
@patw0929 Looks like this is definitely a bug, could you please at least `confirm` us if we are right? We can prepare a fix for this issue and solve it (I've read that you are currently very busy in your job). Thanks for any response.

**Comment by patw0929** [comment]
Yup, thanks guys, you are right! It's a bug.
I'll merge it later. 🙇
