### ISSUE TITLE
value prop doesn't work

### ISSUE THREAD

**Issue by rogeriochaves** [patw0929/react-intl-tel-input#22]
So, apparently the input value state is held inside the component redux, and I can't change it.

My use case is that a have a form using this, but when the user cancels and opens the form again, the same telephone input stay there, and I don't want that. Even if I pass it explicitly like this:

```javascript
<IntlTelInput value='' />
```

It doesn't work. The last value always stays there even if I rerender the component.

Although, the countryCode is always reset to the default one.

**Comment by patw0929** [comment]
I made some fix, could you check it? Thanks!

**Comment by rogeriochaves** [comment]
Yes! It worked like a charm, thank you!
