### ISSUE TITLE
Proposal to upgrade to 5.1.0

### ISSUE THREAD

**Issue by superhit0** [patw0929/react-intl-tel-input#222]
@patw0929 Can we upgrade this repo to `5.1.0` by making utilScript optional & removing `libphonenumber.js` from the dist folder & making webpack load `libphonenumber`  from bundle & chunking those two files.

This is the sample code change I have done to dynamically download the `libphonenumber` in case utilScript is not given.

https://github.com/patw0929/react-intl-tel-input/compare/master...superhit0:util-option?expand=1

We can also start our Changelog with this version.

What are your thoughts?

**Comment by patw0929** [comment]
Good idea! 
Sorry I am still busy at work. I'll try your PR when I get home tonight.

**Comment by patw0929** [comment]
It will worth to try! Please make it as a PR.
And could you make a todo list at this thread?

**Comment by superhit0** [comment]
Sure, I am busy with work too. Lets try this weekend.

**Comment by superhit0** [comment]
@patw0929 
Came up with toDo list for 5.1.0:
- [x] Fix cursor issue
- [ ] Bundle `libphonenumber.js` with `webpack`
- [ ] Remove `libphonenumber` from `dist` [Due to Bundling]
- [ ] Add `ChangeLog`.
- [ ] Update `Readme` if `libphonenumber` removed from `dist`

Please suggest additions/deletions of any ideas.

**Comment by patw0929** [comment]
Awesome!

Maybe we should consider the change of `componentWillReceiveProps` will deprecated in future 16.x release, but if it has lots of change to do, next release is ok too.

**Comment by superhit0** [comment]
Sounds Good, I am adding it to the todo list. Since this is a major change, I would prefer it to go in a `0.1` version upgrade rather than any `0.0.1` upgrade.

**Comment by superhit0** [comment]
I think we should also increase our coverage to `100%`, but that can go later as it will not affect the functionality or usage of the components

**Comment by superhit0** [comment]
Can we close the above list for the upgrade or do we want to add few more things?

According to me, the above changes should not take more than 1~1.5 weeks including merging tasks.


@patw0929 Shall we start on this?

**Comment by patw0929** [comment]
Sure! I think this list is good enough. 
We can start! 🙌 Thanks!

**Comment by patw0929** [comment]
OK, no problem. I will handle it later.

**Comment by patw0929** [comment]
Because of the breaking change, it published as v6.0.0.
