### ISSUE TITLE
validation not working 

### ISSUE THREAD

**Issue by MaheshK02** [patw0929/react-intl-tel-input#228]
import IntlTelInput from 'react-intl-tel-input';
import 'react-intl-tel-input/dist/main.css';
import libphonenumber from 'react-intl-tel-input/dist/libphonenumber.js';
import classnames from 'classnames';

             <div className="form-group">
                      <label className={classnames('control-label', 'labelClass')}>
                                 Contact Number
                       </label>
                        <IntlTelInput
                                    preferredCountries={['in']}
                                    onPhoneNumberChange={ this.handler }
                                    onPhoneNumberBlur={ this.handler }
                                    value= {this.state.contact}
                                    css={ ['intl-tel-input', 'form-control'] }
                                    utilsScript={ libphonenumber }
                                     />
              </div>

utilsScript not working. how to fix it ?

**Comment by superhit0** [comment]
`import 'react-intl-tel-input/dist/libphonenumber.js';`

```
<div className="form-group">
                  <label className={classnames('control-label', 'labelClass')}>
                             Contact Number
                   </label>
                    <IntlTelInput
                                preferredCountries={['in']}
                                onPhoneNumberChange={ this.handler }
                                onPhoneNumberBlur={ this.handler }
                                value= {this.state.contact}
                                css={ ['intl-tel-input', 'form-control'] }
                                utilsScript="libphonenumber.js"
                                 />
          </div>
```

**Comment by superhit0** [comment]
@MaheshK02 Did it work?

**Comment by MaheshK02** [comment]
not working..

**Comment by superhit0** [comment]
did you try the code I gave?

**Comment by MaheshK02** [comment]
yes with the same import line 
import 'react-intl-tel-input/dist/libphonenumber.js';

        <div className="form-group">
                  <label className={classnames('control-label', 'labelClass')}>
                             Contact Number
                   </label>
                    <IntlTelInput
                                preferredCountries={['in']}
                                onPhoneNumberChange={ this.handler }
                                onPhoneNumberBlur={ this.handler }
                                value= {this.state.contact}
                                css={ ['intl-tel-input', 'form-control'] }
                                utilsScript="libphonenumber.js"
                                 />
          </div>

**Comment by superhit0** [comment]
well @MaheshK02 if your code is open-source, post the link to repository, I can have a look at it. Otherwise I am not sure

**Comment by MaheshK02** [comment]
One more issue.
 preferredCountries={[this.state.country_code]}
value change after render but not display in the above code.

**Comment by MaheshK02** [comment]
code is not open source.
if u want u can access my code via teamviewer.
Thanks @superhit0

**Comment by superhit0** [comment]
Sry @MaheshK02  I messed up.

`import 'react-intl-tel-input/dist/libphonenumber.js';`

```
<div className="form-group">
                  <label className={classnames('control-label', 'labelClass')}>
                             Contact Number
                   </label>
                    <IntlTelInput
                                preferredCountries={['in']}
                                onPhoneNumberChange={ this.handler }
                                onPhoneNumberBlur={ this.handler }
                                value= {this.state.contact}
                                css={ ['intl-tel-input', 'form-control'] }
                                utilsScript="libphonenumber.js"
                                 />
          </div>
```

Can you try this?

If this still doesnt work, then we can setup some time.

**Comment by MaheshK02** [comment]
what is the difference in the above code? 
and for this which library(dependencies) I need to install. 

I did this too for classnames.
import classnames from 'classnames';

**Comment by MaheshK02** [comment]
still not working.. i think will setup time for this 4.30pm today?
check facebook

**Comment by MaheshK02** [comment]
@superhit0 it's not working. let me know what to do.

**Comment by superhit0** [comment]
@MaheshK02  If you have your code deployed some where, I can look at it, but if we have to sit together, I wont be available till weekend.

or you can try uploading your code in [gitlab.com](gitlab.com) as a private repository and give me access to look at it.

Private repos are free in gitlab.

**Comment by superhit0** [comment]
@MaheshK02 can we setup some time between 3-4pm IST today ? for the teamviewer chat

**Comment by MaheshK02** [comment]
4 pm IST today
Done

**Comment by superhit0** [comment]
@MaheshK02 ping me on [gitter](https://gitter.im) when you are ready. you can use your github account to login
