### ISSUE TITLE
[Bundle improvement] - Update .npmignore

### ISSUE THREAD

**Issue by JonShort** [patw0929/react-intl-tel-input#231]
Thanks for this library! Really cool implementation of `intl-tel-input` 😄

### The Issue

At the moment the bundled package contains the entire source code because the `.npmignore` is empty.

Would it be possible to add files which are non-essential for library consumers to the `.npmignore`? 
Some example files to exclude (there are more):
```
yarn.lock
.editorconfig
src/
example/
```

I am happy to do this work, or feel free to close this issue if the entire source is bundled for a reason 👍

**Comment by superhit0** [comment]
good idea 👍 . Thanks for pointing it out. We were planning a revamp of the code.

Had a few things to needed to be taken care before we introduce this.
