### ISSUE TITLE
allowDropdown prop not working

### ISSUE THREAD

**Issue by lisdey** [patw0929/react-intl-tel-input#235]
Hello, 
I'm trying to set the allowDropdown to false as the doc says, it should hide the dropdown arrow and the selected flag won't be clickable. However, the flag is still clickable, it hides the arrow, but I can  still click the flag and it will show the countries menu. 

Any thoughts how can I accomplish this? 

Thanks in advance

**Comment by tomegz** [comment]
I'm also having this issue and I submitted a PR.

**Comment by tomegz** [comment]
Steps to reproduce the issue: 

1. Set `allowDropdown` prop to `false`
2. Flag is set on the right side (with no arrow) but I'm still able to click the flag and show country dropdown.
