### ISSUE TITLE
Can not import from Node.js since module build upgrade to webpack 4

### ISSUE THREAD

**Issue by coox** [patw0929/react-intl-tel-input#253]
I am using [react-intl-tel-input](https://github.com/patw0929/react-intl-tel-input) in a universal JavaScript project. When attempting to upgrade from 5.0.7 to 6.0.0, I noticed the following error on the Node.js side:

`ReferenceError: window is not defined`

The error happens at module import time, and seems to be a consequence of the production build now relying webpack 4 (since [`42574fe`](https://github.com/patw0929/react-intl-tel-input/commit/42574fef03cba44df4e12d2b05019e2a6d3268e5)). There is a [known issue](https://github.com/webpack/webpack/issues/6522) in webpack 4 that makes it impossible to create an universal UMD build.

A workaround is suggested in this comment:

https://github.com/webpack/webpack/issues/6522#issuecomment-371120689

It consists in adding the following line to the [webpack production config](https://github.com/patw0929/react-intl-tel-input/blob/master/config/webpack.config.prod.js) of the `IntlTelInputApp` entry:

`globalObject: 'typeof self !== \'undefined\' ? self : this'`

I have tried to fork react-intl-tel-input and test this, but unfortunately I was unable to even produce a build (`npm run build` does tell me that “The dist folder is ready to be deployed.”, but the folder is empty — please let me know if you'd like more details).

Would it be possible to add this workaround to the webpack configuration and release a new version that would be universally importable?

Thank you very much,

**Comment by superhit0** [comment]
@coox can you give me sample code with this to look for the fix?

Just make a universal app with the webpack configs you have and try to import `react Intl`.

That should be enough for me to start looking into it.

Your production code (if not open source) is not required.

Thanks.

**Comment by patw0929** [comment]
With the sample project, I install `react-intl-tel-input` locally by: `yarn add file:../react-intl-tel-input`, and I found:

1. the webpack umd fix works nicely
2. but there is a new issue: `Unhandled Rejection (TypeError): Cannot read property 'bind' of undefined`. (the error occurs at `var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);`)

I think the point 2 is caused by the dynamic import.
Need take some time to figure it out.

**Comment by superhit0** [comment]
For me I see that this works:

```
globalObject: '(window || this)'
```

**Comment by patw0929** [comment]
@coox We fixed the issue and publish as a alpha release v6.1.0-alpha.0.
Could you help to check it? Thank you!

**Comment by coox** [comment]
@patw0929 — Looks like Node.js import works again with 6.1.0-alpha.0 🙂️

**Comment by superhit0** [comment]
@coox @patw0929 as the issue has been resolved.
