### ISSUE TITLE
onPhoneNumberBlur: no access to the Event object

### ISSUE THREAD

**Issue by thomasledoux1** [patw0929/react-intl-tel-input#256]
Hi,

We were happily using this component in our React website, but we encountered an issue now.
We need access to the Event which is thrown by the blur of the input field. 
In the documentation we found the onPhoneNumberBlur, which passes 5 properties (status, value, country, number, id), but not the Event object itself.
We need access to this event because we need to know what the RelatedEvent is of the blur Event.

If it possible to change this?

Thank you.

**Comment by superhit0** [comment]
added event param to the function

made it 
```
(status, value, country, number, id, event)
```

**Comment by patw0929** [comment]
Merged #257, and we've released v6.1.0.

**Comment by thomasledoux1** [comment]
Thank you! We'll start using it in our code right away.
