### ISSUE TITLE
 Can't resolve 'libphonenumber-js-utils'

### ISSUE THREAD

**Issue by imdbsd** [patw0929/react-intl-tel-input#263]
Hi, 
i'm just reinstalled the library to update from 6.0.0 to 6.1.0 and getting error

"Can't resolve 'libphonenumber-js-utils'" in "node_modules\react-intl-tel-input\dist"

i'm trying to downgrade again to 6.0.0 and still facing the issue,

did i need to installed it separately right now?

thank you

**Comment by superhit0** [comment]
do you have a sample code?

**Comment by imdbsd** [comment]
im using it like this on my code

```
import 'react-intl-tel-input/dist/main.css';
import './index.css';

<IntlTelInput
    placeholder="Mobile Number**"
    defaultCountry='gb'
    value={this.state.mobile_number}
    css={['intl-tel-input', 'form-control']}
    onSelectFlag={this.changeMobileCountry}
    onPhoneNumberChange={this.mobileNumberHandler}
    disabled={this.state.isSubmit}
/>
```

**Comment by patw0929** [comment]
@superhit0 I think it is because `libphonenumber-js-utils@8.10.3`'s npm publish has some issue.
The `dist/libphonenumber.js` is not exist in 8.10.3's publish, but 8.10.3-alpha.1 is ok.

**Comment by imdbsd** [comment]
is there any hotfix that i can try to solve this?

**Comment by patw0929** [comment]
@imdbsd Could you try to add `libphonenumber-js-utils@8.10.2` in  `peerDependencies` (`package.json`) first?
Sorry, we will fix it later.

**Comment by superhit0** [comment]
@patw0929 I am not sure because we locked the version to `8.10.2` in the latest release. 
But please @imdbsd can you confirm if the above fix works?

**Comment by imdbsd** [comment]
hi, im trying it but still doesnt get the dist folder in libphonenumber-js-utils

but luckyly i still have the dist folder on other machine and simply put it in the node_modules/libphonenumber-js-utils

is there anything i can help?

**Comment by imdbsd** [comment]
if anyone also land here and facing the issue.

i'm doing a hotfix by placing this dist https://bit.ly/2VPxHXb to node_modules/libphonenumber-js-utils

**Comment by superhit0** [comment]
@imdbsd is there a way I can remote login to your system and see whats happening?

using some software like `teamviewer`? 

if yes, can you reach out to me on gitter? I have the same email @superhit0 over there too.

**Comment by patw0929** [comment]
@imdbsd:
Sorry for the wrong way in previous comment.
As a workaround, please try to install `libphonenumber-js-utils@8.10.2` manually? (By `yarn add` or `npm install --save`). 
It will add `"libphonenumber-js-utils": "8.10.2"` in `dependencies` part in `package.json`.

@superhit0:
Oh, as I know, only the application's own `yarn.lock` file is respected, but not the libraries'. ([reference](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/))
So, the next step to fix this, we should publish a new release of react-intl-tel-input, which is set the workable libphonenumber-js-utils version in package.json. (maybe libphonenumber-js-utils@8.10.3-alpha.1)

**Comment by superhit0** [comment]
@patw0929 Can you `npm unpublish` the libphonenumber-js-utils of version `8.10.3` only?

I can publish a new module from ci

**Comment by imdbsd** [comment]
looks like it fix now after @superhit0 request to unpublish the libphonenumber-js-utils@8.10.3

the dist folder is there

i will close this.

Thanks guys.
