### ISSUE TITLE
css prop does not work

### ISSUE THREAD

**Issue by plamenh** [patw0929/react-intl-tel-input#264]
css prop is completely ignored:

input class is non-existent, while container class is ignored (not changed/added).

```
<IntlTelInput 
	defaultCountry={i18n.language == 'bg' ? 
		'bg' : 
		i18n.language == 'en-gb' ? 
			'gb' : 
			'auto'
	} 
	css={['intl-tel-input', 'form-control']}
/>
```
and

```
<IntlTelInput 
	defaultCountry={i18n.language == 'bg' ? 
		'bg' : 
		i18n.language == 'en-gb' ? 
			'gb' : 
			'auto'
	} 
	css={['randomClass', 'form-control']}
/>
```

both result in the same

`<div class="intl-tel-input allow-dropdown">...<input type="tel" autocomplete="off" class="" name="" id="" placeholder="048 123 456" value=""></div>`

Any input is appreciated. Thanks.

**Comment by plamenh** [comment]
Sure, here it is:

![image](https://user-images.githubusercontent.com/14073311/51799216-9c212e80-2227-11e9-9177-f8ca1fc4be2c.png)
![image](https://user-images.githubusercontent.com/14073311/51799218-a04d4c00-2227-11e9-95df-7a9bdf3badc9.png)

Might there be an issue, if I am using React 16.x? This is the only thing I can think of.

**Comment by plamenh** [comment]
Apparently, the css prop gets stripped somewhere along the way, as the default prop is used for css.

![image](https://user-images.githubusercontent.com/14073311/52108078-8fbf1c00-2601-11e9-90f1-8113c6a1565f.png)

**Comment by nutboltu** [comment]
@plamenh It's interesting that I couldn't reproduce it using [create-react-app](https://github.com/facebook/create-react-app). Can you please try into another repo? I think there's something else in your application that stopped updating the css props.

**Comment by jjun14** [comment]
@plamenh are you using [styled-components](https://www.styled-components.com/docs/api#css-prop)? 

I ran into a similar issue and noticed that the _**css**_ prop was not being passed correctly because styled-components also uses a  _**css**_ prop to identify which components to decorate which explained the issue for me. Forking and patching for now adding adding an alternative prop name to avoid something like this could be a nice addition in the future!

**Comment by plamenh** [comment]
@jjun14 yes, I am.

Yeah, I figured last resort would be to fork. But, come on, styled components is not something that is rarely used. Plus, using 'css' as the name of your prop is not a good idea in any case. How about cssClasses? Even better would be to explicitly name the classes for the two containers, i.e. containerClassName and inputClassName.

**Comment by patw0929** [comment]
@jjun14 & @plamenh: Thank you for pointing out the root cause and providing better naming.  
I've opened the pull request #271.

**Comment by patw0929** [comment]
Merged and released as v7.0.0.

**Comment by jjun14** [comment]
@patw0929 you may want to update README to reflect changes 💯

**Comment by patw0929** [comment]
Oops! Updated. Thank you.
