### ISSUE TITLE
Tel input keeps getting focus

### ISSUE THREAD

**Issue by thomasledoux1** [patw0929/react-intl-tel-input#266]
Hi,

We started using version 6.1.0 to be able to use the event itself when the onPhoneNumberBlur is triggered.
We currently have the following code setup:
 
```js
<IntlTelInput
  className={this.getFormControlClasses('personalInformation.Phone')}
  type="tel"
  fieldId="personalInformationForm-phone"
  defaultCountry="auto"
  fieldName="Phone"
  placeholder={dictionary.get('Features.GlassBooking.PersonalInfo.Phone')}
  defaultValue={this.state.Phone}
  data-phonenumber={this.state.Phone}
  css={['intl-tel-input', this.getFormControlClasses('personalInformation.Phone')]}
  preferredCountries={['be', 'lu']}
  onlyCountries={['al', 'ad', 'at', 'by', 'be', 'ba', 'bg', 'hr', 'cz', 'dk',
    'ee', 'fo', 'fi', 'fr', 'de', 'gi', 'gr', 'va', 'hu', 'is', 'ie', 'it', 'lv',
    'li', 'lt', 'lu', 'mk', 'mt', 'md', 'mc', 'me', 'nl', 'no', 'pl', 'pt', 'ro',
    'ru', 'sm', 'rs', 'sk', 'si', 'es', 'se', 'ch', 'ua', 'gb']}
  utilsScript={'libphonenumber.js'}
  initialCountry={'auto'}
  geoIpLookup={(data) => { this.geoIpLookup(data); }}
  onPhoneNumberBlur={(status, value, country, number, id, event) => this.handlePhoneBlur(event, number)}
/>
```

However, when we focus any other (input) element on the page, the focus keeps going to the telephone input field. This behavior did not happen before we upgraded to 6.1.0. Do you have any idea why this could be happening? This only occurs on Safari (mobile and desktop).

**Comment by patw0929** [comment]
Thanks for point it out. It might be caused by #221.
As workaround, I comment out this part in TelInput.js and seems like works fine Safari:

```js
  componentDidUpdate() {
    this.tel.setSelectionRange(
      this.props.cursorPosition,
      this.props.cursorPosition
    );
  }
```

Could you help to fix it? @superhit0 

For clarify, I attach the error situation screenshot here:
<img src="http://g.recordit.co/Oh6L5CHFuK.gif" />
(I use Safari here)

**Comment by superhit0** [comment]
@patw0929 Boss I am very busy this month, like neck deep in work, I am not sure I would be of any help this month.

PS:- If I get some time on weekends, I will try to pitch in.

**Comment by jlibrun22** [comment]
I downgraded to 5.0.7 to remediate this issue.

**Comment by patw0929** [comment]
@thomasledoux1 @jlibrun22:
We've published a hotfix as v6.1.1, please help to verify it 🙇

**Comment by loris** [comment]
Also confirm that `6.1.1` fixed the issue on our end

**Comment by thomasledoux1** [comment]
6.1.1 fixed the issue on our side too!
Thank you for the swift response.
