### ISSUE TITLE
disabled state doesn't update an input field v6.1.0

### ISSUE THREAD

**Issue by Tsyklop** [patw0929/react-intl-tel-input#268]
I pass to an IntlTelInput component `disable={inputEnabled}`, `inputEnabled` is boolean variable, in the first time it is true and the IntlTelInput is disabled but when the `inputEnabled` became false the IntlTelInput still disabled I can't modify input field.

**Comment by patw0929** [comment]
Thanks for reporting this issue! We've fixed it and publish it as v6.1.1.
If it still has bugs, please reopen it.
