### ISSUE TITLE
React shouldn't be a dependency.

### ISSUE THREAD

**Issue by Nic128** [patw0929/react-intl-tel-input#28]
I encountered a problem when I upgraded my app to react 0.14. Installing react-intl-tel-input would install a second react 0.13.3, then at bundling/runtime, it would break. My solution was to modify the package.json and put react as a devDependencies, then I could install/run it with no conflicts. I am also using npm 3 to install.

Could you release a 0.0.12 and 1.2.5 with that fix?

**Comment by patw0929** [comment]
Hi @Nic128,

I've fixed it, and released 0.0.12 & 1.2.5.
Thank you for your advice! :)

**Comment by Nic128** [comment]
Thanks. Everything works now.
