### ISSUE TITLE
bash commands in contributing(readme) highlighted

### ISSUE THREAD

**Issue by Parikshit-Hooda** [patw0929/react-intl-tel-input#293]
The bash commands of `npm run test` and `yarn test`  have 'test' highlighted in them. Is this by design as the markdown tells that they are bash commands. Or should we remove the syntax highlight to make it better.
## Expected Behavior

The 'test' should not get highlighted.
## Current Behavior

the 'test' turns blue
## Possible Solution

remove the 'bash' indicator from the markdown. Happy to open a PR as part of hacktoberfest.
## Steps to Reproduce

1. See the contributing section in Readme.md
2.
3.
4.

Code:

```js
```

## Environment

* Version:
  
* Browser:

**Comment by bhumijgupta** [comment]
Can i work on this?

**Comment by scheleon** [comment]
Can I take this one?
