### ISSUE TITLE
React 0.14 support

### ISSUE THREAD

**Issue by Nic128** [patw0929/react-intl-tel-input#30]
Can you make a 2.0 and 0.0.13 release for react 0.14 support? I'm getting warnings mostly.

**Comment by patw0929** [comment]
Hi @Nic128, could you help me to try these branches works or not?

https://github.com/patw0929/react-intl-tel-input/tree/upgrade-react-0.14
https://github.com/patw0929/react-intl-tel-input/tree/0.0.x-with-react-0.14

Thanks!

**Comment by Nic128** [comment]
For this branch, https://github.com/patw0929/react-intl-tel-input/tree/0.0.x-with-react-0.14, you also need to put react-dom in your components that use findDOMNode (IntlTelInput.js and CountryList.js). Plus, in the package.json, if we put the peerDependencies up to date, can we delete the react 0.13.3 in the devDependencies?

Will test the other one.

**Comment by Nic128** [comment]
Same comments for this branch. https://github.com/patw0929/react-intl-tel-input/tree/upgrade-react-0.14

**Comment by patw0929** [comment]
Fixed. Please take a look again, thanks!

**Comment by Nic128** [comment]
Warnings for react have gone away for both branches, it's good. Now that react 0.14.1 is out, let's put the peerDependencies to:

````javascript
"peerDependencies": {
    "react": "^0.14.0",
    "react-dom": "^0.14.0"
  },
````

This way npm won't give warnings if we don't use 0.14.1.

**Comment by onedesert** [comment]
Hey there, I was trying to wrap the Intl-tel-input into a react component and I found this project. I'm currently using react 0.14.0 and I think that usage of ^0.14.0 is a proper solution. I thinks I'll use this component in my project. Thanks.

**Comment by patw0929** [comment]
Hey guys, I have revised it. Please check it. 
Thanks again!

**Comment by Nic128** [comment]
upgrade-react-0.14 is fine. can you update 0.0.x-with-react-0.14 with the same peerDependencies?

**Comment by patw0929** [comment]
Sure. I have updated it.

**Comment by Nic128** [comment]
Everything is good.

**Comment by patw0929** [comment]
Merged. Is everything ok still?

**Comment by Nic128** [comment]
Good for me.

**Comment by patw0929** [comment]
Issue closed.
If you still find issues, please open a new issue. Thank you guys.
