### ISSUE TITLE
Setting up automated releases using `semantic-release`

### ISSUE THREAD

**Issue by mcataford** [patw0929/react-intl-tel-input#321]
To ensure that our dependents can benefit from work being done on the library, we should set up `semantic-release`. It's pretty much a no-work setup as long as the tokens are there.

@patw0929 Perhaps you could assist since you're the token-holder release-wise. :) I'd be happy to set up everything else once the secret is stored in Travis. From there on out, fixes and improvements would reach users in a pinch.

**Comment by patw0929** [comment]
Thanks a lot! 🙌 
What kind of tokens? GitHub personal access token/npm token?
I'll set it up when I back home later. :)

**Comment by mcataford** [comment]
I can see on Travis that there's a `GH_TOKEN` registered, I can only assume that that token is valid and would allow `semantic-releases` to add releases to the repo, so we'd just need an NPM token to be set up on there as well!

**Comment by mcataford** [comment]
Thanks for being so responsive!

**Comment by patw0929** [comment]
@mcataford I've added `NPM_TOKEN` to Travis CI! 😄

**Comment by mcataford** [comment]
Wonderful,! I'll set up the automated releases today! Thank you!
