### ISSUE TITLE
containerClassName misbehaving

### ISSUE THREAD

**Issue by tkolo** [patw0929/react-intl-tel-input#344]
I've been working on validation feedback and noticed that it misbehaves when used with this component. After setting invalid class through containerClassName and then unsetting it again, it sticks, for reasons that I couldn't really point out during my whole-afternoon debug session.

Here's a short repro of the bug: https://codesandbox.io/s/hungry-browser-fvc9z
If the css styles didn't load, I'm sorry, I don't know what's going on, sometimes they do, sometimes they don't.
Click the button twice to reproduce (if styles didn't load, it's at the bottom of the page)

## Expected Behavior
the control should get invalid class once it's set through containerClassName and then lose it once empty string is passed in contanierClassName.

## Current Behavior

Once setting the invalid class, it sitcks, and I have no idea why

## Possible Solution

¯\\\_(ツ)_/¯

## Steps to Reproduce

See the link above 

## Environment

* Version: v8.0.2
  
* Browser: Firefox 77, also tested on Chrome 81

**Comment by mcataford** [comment]
Hi @tkolo!

Thanks for flagging the issue! I took a quick look at the journey the `containerClassName` takes and have a few ideas on what might be causing this. I'll should be able to circle back with a tentative fix later today! :crossed_fingers:

**Comment by tkolo** [comment]
Thank you, no rush though as this can be very easily work-arounded by wrapping the component in `div` and simply styling said wrapping `div` instead

**Comment by mcataford** [comment]
I've put up a PR that seems to address the issue you described. I will pull down the CodeSandbox you linked so that I can test it directly with your example later today. :rocket:

**Comment by mcataford** [comment]
@tkolo Tested out with your sandbox, the fix indeed addresses the issue. I just merged it in, so it should be out as `8.0.3` shortly. Will close the issue on release.

**Comment by mcataford** [comment]
`react-intl-tel-input@8.0.3` is now out and contains the fix for the issue you reported! :tada: Closing this issue for now, don't hesitate to reach out if you experience more issues!
