### ISSUE TITLE
Input values returned should not be formatted, even whenthe  format props is set to true

### ISSUE THREAD

**Issue by ogheneovo12** [patw0929/react-intl-tel-input#361]
Input values returned should not be formatted, even when the format prop is set to true,
## Expected Behavior

i should be able to get unformatted values from both the value and the onPhoneNumberChange props, the formating is only meant for the user or user experience, I should be able to get the raw user input returned, even with formatted sets to true
## Current Behavior
i kept getting the formatted input, which apparently makes the values useless, or counter-intuitive as i would have to reformat the input again,

**Comment by lo2aai** [comment]
Did you find anything related to this issue ?
