### ISSUE TITLE
Switching CI something more accessible / easier to handle

### ISSUE THREAD

**Issue by mcataford** [patw0929/react-intl-tel-input#375]
I'm looking at getting back on the horse and merging some changes that were in flight here, notably some dependency upgrades + the Typescript-enabling change so that we can progressively trim away at the bigger technical debt issues in the library code. Having a handle on CI is a big part of that.

As of June 2021, the TravisCI service has changed hands and doesn't seem to be building this actively. Since the pipeline is simple enough, migrating it to Github Actions would make rapid development much easier. A couple of things that come to mind would be the need to add matrix testing for Node versions, React versions and all. Aside from that, it would gather all the relevant information in one place (i.e. build results without needing a third party).

@patw0929 I'd definitely like your take on this -- if you aren't against it, I'd love to make quick work of that move (otherwise, I'd love to know more about your thoughts on CI for this).

**Comment by patw0929** [comment]
Sorry for didn't notice messages from this repo for a long time.
I've tried running the `yarn` and bumping the error too.
I agree with you, it's time to upgrade the node/react/related dependencies/CI first. Thank you for helping! 🙇

**Comment by mcataford** [comment]
Neato.

#374 should take care of the build errors so I'll merge that in now, and I'll look at CI next so that we can make the next couple of changes with the warmth reassurance of :heavy_check_mark: s on the builds

**Comment by mcataford** [comment]
Got some CI going in #376. :rocket: I'll bring it up to parity with the old pipeline today and merge it in so we can move on to greater things.

**Comment by mcataford** [comment]
Merged #376, CI is now live. :rocket: 

One action item on your end @patw0929 : the `NPM_TOKEN` secret should be updated in the repository secrets. Until then, new releases via CI can't come out. Once update, the builds should pick it up.

**Comment by patw0929** [comment]
Oh cool! I've added `NPM_TOKEN` to this repo's env variables.

**Comment by mcataford** [comment]
Neat! Finishing up some changes that should trigger a build, which in turn should pick up the token!

**Comment by patw0929** [comment]
Oops, it seems failed again, I put `NPM_TOKEN` into repo secrets now. (in env secrets last time)

**Comment by mcataford** [comment]
Looks like it's a success! Closing this issue now that CI is up and running.
