### ISSUE TITLE
Class manipulation causes style bug for invalid input

### ISSUE THREAD

**Issue by rpastorelle** [patw0929/react-intl-tel-input#40]
When you type an invalid character the class manipulation is mangling the class attribute in a bad way. You can see this bug on the [demo page](http://patw0929.github.io/react-intl-tel-input/) by typing some letters very quickly. 

The class attribute of `form-control` will soon become `          form-controliti-invalid-key  `

This is in part due to the `removeClass` function being careless. And mostly due to the setTimeout call inside of `handleInvalidKey`.

This could perhaps be accomplished quite simply with underscore: 

```
removeClass(el, klass) {
  var index,
      elClasses = el.className.split(' ');

  return _.without(elClasses, klass);
}
```

**Comment by patw0929** [comment]
Fixed in v2.0.4. 

If you are still experiencing this problem, please reopen this issue.
Thank you.
