### ISSUE TITLE
Phone number input is focused on page load

### ISSUE THREAD

**Issue by dsteinbach** [patw0929/react-intl-tel-input#43]
Not sure why but the phone input is focused by default when the page loads. This looks weird on my form because phone input is in the middle of my form.

**Comment by patw0929** [comment]
Got it. Fixed in v2.0.5 and v0.0.17. 

If you are still experiencing this problem, please reopen this issue.
Thank you :)

**Comment by dsteinbach** [comment]
Awesome thanks!

**Comment by BenNG** [comment]
Hi there !

I was wondering: What is the status of this issue because I still experiencing the problem with version 2.7.1.

Thanks !
