### ISSUE TITLE
React & ReactDOM are included in dist/main.js

### ISSUE THREAD

**Issue by wakeless** [patw0929/react-intl-tel-input#44]
The React and ReactDOM are part of dist/main.js

This causes react to be double loaded which causes issues.

**Comment by patw0929** [comment]
Thanks for your report! But when I removed the react & react-dom external script from the example page (`index.html`), there is a JavaScript error: `Uncaught ReferenceError: React is not defined`... Seems that the `React` object is not in the `dist/main.js`, but in the external script.

And my webpack external setting was:

```
  externals: {
    'react': {
      root: 'React',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react'
    },
    'react-dom': {
      root: 'ReactDOM',
      commonjs2: 'react-dom',
      commonjs: 'react-dom',
      amd: 'react-dom'
    }
  },
```

I think that this setting could avoid bundling the React & React-DOM into `dist/main.js`.

Any advice?

**Comment by janmarek** [comment]
@wakeless I don't think it is true. Do you have a proof so this issue can be confirmed?

**Comment by brunops** [comment]
Doesn't seem to be the case, this issue can probably be closed.
