### ISSUE TITLE
Multiple inputs on the same page share events

### ISSUE THREAD

**Issue by lukemcgregor** [patw0929/react-intl-tel-input#50]
If you have two inputs on the same page, their state/events are linked. Anything that happens on one happens on the other

**Comment by xiankai** [comment]
Encountering the same problem. Perhaps an additional key can be added to the action to specify which input is dispatching actions as well as tracking separate inputs?

**Comment by patw0929** [comment]
Really sorry for the late reply. Unfortunately I'm quite busy at company projects recently.
Pull requests are welcome if you have any idea :)

**Comment by dsteinbach** [comment]
+1 :(

**Comment by jasonxp** [comment]
I'm also having this problem. Has anyone found a workaround? @lukemcgregor @xiankai @dsteinbach

**Comment by xiankai** [comment]
I have made a fix based on changing the redux structure to store each instance's information under a unique id. You can see this in the example build under my fork.

https://github.com/xiankai/react-intl-tel-input

However the downside is that you'll have to maintain a unique `id` prop to pass to each input as I have not found a way to generate them automatically.

@patw0929 Would this be suitable? If so I can write some tests and update the documentation before making a pull request.

**Comment by patw0929** [comment]
Wow! @xiankai Thank you for your help! It works!

But I noticed that there still has one issue:
If we have two tel-input components here (like in your example.js), the first one wouldn't show the flag (still in gray), seems like the first auto-country is not working?

Did you met the same issue?

**Comment by xiankai** [comment]
@patw0929 Hmm I never noticed that since it doesn't occur in my work where I am using it (which also doesn't have the `defaultCountry` prop).

I could give it a further look later.

**Comment by patw0929** [comment]
I made a PR (#74) here.

Because we had merged lots of code, so I copied code again from @xiankai's fork into this PR.
I had updated the example and tests also.

Can anyone help to check it works or not? And any advice? 
Thanks a lot!

**Comment by janmarek** [comment]
Guys, maybe I have a better solution. The redux store is used for handling the internal state of each component. Therefore each react-intl-tel-input instance should have its own redux store. Problem solved without the need of additional id attribute.
