### ISSUE TITLE
defaultValue behaves differently for US based numbers (+1201.....)

### ISSUE THREAD

**Issue by mordra** [patw0929/react-intl-tel-input#51]
When I set the defaultValue to be something like "+12015555555" or "+12025555555" the onPhoneNumberChanged handler is called twice with the last call being:
false "(202) 555-5555" Object {} ""

When the default value does not start with the +, then it recognises the number:
true "1 202-555-5555" Object {name: "United States", iso2: "us", dialCode: "1", priority: 0, areaCodes: null} "+12025555555"

This behaviour is reversed for all other countries I've tried (gb, ca, au), ie when the number is preceeded with a +, the onPhoneNumberChanged returns the correctly detected country code and number.

It seems that defaultCountry does not affect this behaviour, I've run the same tests with it set to the correct country, a different country, a empty string or not even declaring it and it has no effect.

My workaround is atm, if the country code I'm storing is 'us' then I regex remove the + from the number.

**Comment by patw0929** [comment]
Fixed in v2.0.7.
