### ISSUE TITLE
Invalid defaultCountry throws an exception that cannot be caught

### ISSUE THREAD

**Issue by mordra** [patw0929/react-intl-tel-input#52]
If you create a IntlTelInput with a invalid country code, and try to interact with the control, every change event is met with the error:
Uncaught Error: No country data for "ob"

I don't know how to intercept this as the event is kicked off by (ReactEventListener.dispatchEvent	@	ReactEventListener.js:204) and fails in the libphonenumber/util.js

And the UI doesn't respond (i.e selecting another flag) to overwrite the incorrect code

**Comment by patw0929** [comment]
Fixed in v2.0.7.
