### ISSUE TITLE
Auto focus on load component

### ISSUE THREAD

**Issue by danielnass** [patw0929/react-intl-tel-input#59]
If you load <a href="http://patw0929.github.io/react-intl-tel-input/">demo page</a>, you can see the intl-tel-input component will get the focus automatically.

This can be good in demo page, but if you put component in middle of a form, autofocus will mess with tabindex.

To avoid this, just pass false in selectFlag function in react-intl-tel-input/src/containers/IntlTelInputApp.js at line 261.

this.selectFlag(this.props.defaultCountry || ''**, false**);

```javascript
  // set the initial state of the input value and the selected flag
  setInitialState() {
    let val = this.props.defaultValue || '';

    // Init the flag setting
    this.selectFlag(this.props.defaultCountry || '', false);

    // if there is a number, and it's valid, we can go ahead and set the flag, else fall back to default
    if (this.getDialCode(val)) {
      this.updateFlagFromNumber(val);
    } else if (this.tempCountry !== 'auto') {
      // check the defaultCountry option, else fall back to the first in the list
      let defaultCountry = this.tempCountry;
      if (!this.tempCountry) {
        defaultCountry = (this.preferredCountries.length) ? this.preferredCountries[0].iso2 : this.countries[0].iso2;
      }
      this.selectFlag(defaultCountry, false);

      // if empty, insert the default dial code
      // (this function will check !nationalMode and !autoHideDialCode)
      if (!val) {
        this.updateDialCode(this.selectedCountryData.dialCode, false);
      }
    }

    // format
    this.updateVal(val);
  }
```
Taking advantage this, how can I contribute to code directly without creating a issue here?

Thanks :)

**Comment by patw0929** [comment]
Hi @danielnass,

You can fork this repo to your account, and then creating a new hotfix branch, committing your fixing code, then your can create a pull request.

Looking for your pull request!
Thank you!
