### ISSUE TITLE
App should not have to depend on SASS

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#62]
First of all, thanks for this really good component.

I'm having problems with the dependencies though. Using the component should be as easy as `var IntlTelInput = require('react-intl-tel-input');`, the app using it shouldn't know (or care) that is uses SASS. Same thing for the `libphonenumber.js` dependency.

Would bundling everything (`.js`, `.css` and images) into ONE file be in the interest of the project?

**Comment by brunops** [comment]
I may be wrong, but it actually seems like these dependencies just bubble up to the actual App that is using it.. which must be using `webpack` and have the applicable loaders.

**Comment by patw0929** [comment]
Hi @brunops,

Thanks for the advice. I'm still working on it. :stuck_out_tongue: 
But I think the `libphonenumber.js` and images should be bundled into one file. First, including `libphonenumber.js` is a optional function, if anyone want to use it, he/she can set the file path in `utilsScript` attribute.
And the images, I think they are too large to be bundled in the js file as a base64 string.

I'm still stuck on it, and I'm not sure if I misunderstood your advice. Maybe you can give me some advice and the PRs are welcomed too. Thank you!

**Comment by brunops** [comment]
There may be a better way, but what I was trying to say is that the only way I managed to use the component was by requiring it in an App that has `webpack` configured with `babel-loader`, `node-sass`, `sass-loader`, `file-loader`, `url-loader`, `style-loader`, `css-loader` and `image-webpack-loader` ... so a loot of dependencies on another app

Is the final `dist/main.js` a webpack bundle? In which case we could potentially bundle the style together, so at least the sass dependencies don't apply... 

As per bundling the images, I agree with you, base64 makes the file too big

**Comment by patw0929** [comment]
Hmmm.. I made some revise on it: PR: #65.

**Comment by brunops** [comment]
Thanks! #65 worked for me :+1:

**Comment by patw0929** [comment]
Published as v2.0.11.

If you have any problem, please reopen/create a issue.
Thank you :)
