### ISSUE TITLE
Configurable country list data

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#68]
Hey, I have the country data from a different source and would really like to be able to map it and pass it to the component instead of the hard coded `AllCountries.js` values. Is that a feature that you would be willing to add?

I was thinking that the actual data in `AllCountries.js` could live separately from the mapping function, this way it could be possible to pass the data down that defaults to the list living there in case nothing is provided.

**Comment by patw0929** [comment]
Thank you for your idea! 
But I think this feature seems not to be a common usage for everyone, so I would not like to add this feature in this current time. Maybe in the feature, there are really requests of it, then we can reopen & implement this feature.

**Comment by brunops** [comment]
Well, it's definitely a big requirement for me. I'll see if I can implement it and send a PR so you can evaluate it..
