### ISSUE TITLE
Component does not work independently

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#69]
Probably not a common use case, but the component doesn't work independently in case there is more than one in the page. 

e.g., if you render two `IntlTelInput` components on the same page and click one of them, both expand

<img width="229" alt="screen shot 2016-02-28 at 1 39 10 am" src="https://cloud.githubusercontent.com/assets/1735844/13378452/21ff6520-ddbc-11e5-90e8-d5ba920de65b.png">
<img width="470" alt="screen shot 2016-02-28 at 1 39 15 am" src="https://cloud.githubusercontent.com/assets/1735844/13378453/21ffafbc-ddbc-11e5-9719-f10571b4f928.png">

**Comment by patw0929** [comment]
Same issue:
https://github.com/patw0929/react-intl-tel-input/issues/50

:cold_sweat:

**Comment by brunops** [comment]
oh, sorry about that, didn't see it
