### ISSUE TITLE
constructor should not mutate state

### ISSUE THREAD

**Issue by brunops** [patw0929/react-intl-tel-input#79]
I'm getting a warning when using the component
`Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.`

It seems like `constructor` method is dispatching an action, and thus mutating state in https://github.com/patw0929/react-intl-tel-input/blob/master/src/containers/IntlTelInputApp.js#L132

`getInitialState()` should be used instead ... see a similar issue in this discussion see https://github.com/acdlite/redux-router/issues/171#issuecomment-155570297

**Comment by patw0929** [comment]
Seems that I should move it from `constructor` to `componentDidMount`. PR: #80.
