### ISSUE TITLE
Getting React render error when including IntlTelInput element

### ISSUE THREAD

**Issue by tomasmcguinness** [patw0929/react-intl-tel-input#82]
I have a ReactJS component, which renders a IntlTelInput component.

I'm using Browserify and Babelify to create the JS. At the top of my component, I have

```
var IntlTelInput = require('react-intl-tel-input');
require('file?name=libphonenumber.js!./../../../node_modules/react-intl-tel-input/dist/libphonenumber.js');
```

Then, in my component's render method I have this

```
<div className="required field">
    <IntlTelInput css={['intl-tel-input']} utilsScript={'libphonenumber.js'} onPhoneNumberChange={this.handleSMSChange}></IntlTelInput>
</div>
```

Unfortunately, the browser spits an error when I try to view the page

```
 Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)
```

Remove the IntlTelInput element and everything is fine.

Would you be able to guide me to fix this problem?

**Comment by brunops** [comment]
Try passing two parameters to `css` (they're internally translated to HTML classes)

so, three options:
*like the example* - `css={['intl-tel-input', 'form-control']`

*different css class* - `css={['intl-tel-input', 'foo']`

*no css prop* - just remove it

**Comment by ddanilets** [comment]
bypassed it with `var IntlTelInput = require('react-intl-tel-input').default; `

**Comment by janmarek** [comment]
This might be issue with Babel 6. 

Try import instead of require or [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports)

```js
import IntlTelInput from 'react-intl-tel-input';
```
