### ISSUE TITLE
Remove Redux

### ISSUE THREAD

**Issue by janmarek** [patw0929/react-intl-tel-input#89]
I love redux but I don't think it is useful on such a small component. It makes sense to me to keep the state in one place but I think the place should be App or IntlTelInputApp component.

**Comment by patw0929** [comment]
I have made a branch of removing redux here: https://github.com/patw0929/react-intl-tel-input/tree/feature/remove-redux
(But without test script)

**Comment by janmarek** [comment]
Nice. 

I have noticed two things in IntlTelInputApp.js

1) I would place all fields above methods.
2) You don't have to put unchanged fields to setState

```js
this.setState({
  one: this.state.one,
  two: 'two'
})
```

and 

```js
this.setState({
  two: 'two'
})
```

is the same.

But it does not merge objects recursively.

```js
// state before
// {a: {b: 1, c: 2}, d: 3}

this.setState({a: {b: 2}})

// state after
// {a: {b: 2}, d: 3}
```

**Comment by patw0929** [comment]
Updated in #96.

I don't understand the the first thing you mentioned, could you explain it in detail to me?
Thanks for your comment.

**Comment by janmarek** [comment]
```js

class IntlTelInputApp {

  static propTypes = ...

  // all fields are usually defined here

  constructor() {...}

  someOtherMethod() {...}

  // fields
  autoCountry = ''; // <---
  tempCountry = ''; // <---
  startedLoadingAutoCountry = false; // <---

}

**Comment by patw0929** [comment]
But if we revise that, the eslint result will be:

```
71:3  error  autoCountry should be placed after getNumber  react/sort-comp
```

:thinking:

**Comment by janmarek** [comment]
oh wow. It seem they missed the fact you can have non-static fields in javascript class.

One possible solution is to move field definitions to constructor. Or ask eslint team to fix this issue.

**Comment by patw0929** [comment]
OK, Updated... I have moved the field definitions into `constructor`.

**Comment by patw0929** [comment]
This feature is released in v.2.4.0.
