### ISSUE TITLE
`Uncaught TypeError: Cannot read property 'parentNode' of null`

### ISSUE THREAD

**Issue by cagarweyne** [patw0929/react-intl-tel-input#99]
I managed to add the component into my form, even though getting the value from the component was a little fiddly. However, I am now getting the above error - it's not breaking anything else, but this logs to the console and I'd like to resolve it.

**Comment by patw0929** [comment]
Could you provide some code for me to reproduce this issue?

**Comment by cagarweyne** [comment]
@patw0929 I managed to fix the error.
